name: Windows Latest
on:
  workflow_dispatch:

jobs:
  Windows-RDP:
    runs-on: windows-latest
    steps:
      - name: Download and Extract EasyTier
        run: |
          Invoke-WebRequest https://github.com/EasyTier/EasyTier/releases/download/v2.3.2/easytier-windows-x86_64-v2.3.2.zip -OutFile EasyTier.zip
          Expand-Archive -Path EasyTier.zip -DestinationPath .\EasyTier -Force
          Remove-Item -Path "EasyTier.zip"

      - name: Configure Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Administrator Password
        run: |
          $securePassword = ConvertTo-SecureString "${{ secrets.RDP_PASSWORD }}" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $securePassword
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

      - name: Start EasyTier Tunnel
        continue-on-error: true
        run: |
          .\EasyTier\easytier-windows-x86_64\easytier-core.exe `
            --hostname "GithubActions-Runner" `
            --instance-name "GithubActions-Runner" `
            --dhcp `
            --listeners "tcp://0.0.0.0:11010" `
            --listeners "udp://0.0.0.0:11010" `
            --rpc-portal "0.0.0.0:15888" `
            --network-name "${{ secrets.EASYTIER_NETWORK_NAME }}" `
            --network-secret "${{ secrets.EASYTIER_NETWORK_SECRET }}" `
            --peers "tcp://public.easytier.top:11010" `
            --default-protocol "tcp" `
            --latency-first `
            --multi-thread `
            --bind-device true `
            --enable-kcp-proxy `
            --compression zstd
        env:
          EASYTIER_NETWORK_NAME: ${{ secrets.EASYTIER_NETWORK_NAME }}
          EASYTIER_NETWORK_SECRET: ${{ secrets.EASYTIER_NETWORK_SECRET }}

      - name: Delete old workflow run
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
